title: Harrison Ronald Hickman
<img src="index.md/assets/me_delivering_presentation.png" width="150">
description: 07961 395574 | hrhickman17@gmail.com | 2531348@chester.ac.uk | N1147002@ntu.ac.uk |
theme: jekyll-theme-minimal
